[package]
name = "async-obdc-mssql-core"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiberius = "0.8.0"
futures = {version = "0.3.21" }
tokio = {version = "1.17.0", features = ["full"]}
tokio-util = {version = "0.7.1", features = ["full"]}
anyhow = "1.0.56"